- name: Ansible task 1
  hosts: all

  tasks:
  - name: Creating Docker repository
    yum_repository:
      name: Docker
      description: Docker 
      baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
      gpgcheck: no
      
  - name: Installing Docker
    package:
      name:
        - "docker-ce-18.09.1-3.el7.x86_64"
      state: present

  - name: enabling docker service
    service:
      name: "docker"
      state: started
      enabled: yes

  - name: Docker SDK for python3
    command: pip3 install docker

  - name: Creating mount path for Docker Container
    file:
      path: /root/ansible
      state: directory

  - name: Copying html files
    copy:
      src: "/root/task.html"
      dest: "/root/ansible/"

  - name: Launching container using HTTPD Image
    docker_container:
      name: mm2
      image: httpd
      state: started
      exposed_ports:
      - "80"
      ports:
      - "808:80"
      volumes:
      - /root/ansible/:/usr/local/apache2/htdocs/

